---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10"  --node-name master --pod-network-cidr=192.168.0.0/16
  when: installed is changed

- name: Create .kube folder
  become: yes
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0777

- name: Copy admin.conf file
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/vagrant/.kube/config

- name: Change admin.conf owner
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  copy: 
    dest: "join" 
    content: "{{ join_command.stdout_lines[0] }}"
    
- name: unmount shared folders
  mount:
    path: /opt/scripts
    state: absent 
